### PR TITLE
GetAuctionItemClasses was removed

### PR DESCRIPTION
**Pull request by Ketho**
https://eu.battle.net/forums/en/wow/topic/17615303787

### CODE REVIEW

**Comment by jabernat** [comment]
Thanks for your fix, Ketho. How would you like to continue maintaining GuildBankSearch? I can transfer the WoWInterface and CurseForge projects to you, but I need to know your CurseForge username if you want ownership there too.

**Comment by Ketho** [comment]
Hey Saiket, I'd indeed like to maintain GuildBankSearch for you. On another note, I wasn't sure where the actual repo was (CurseForge/Github) and was a bit surprised you'd see my push request.

https://www.curseforge.com/members/Ketho
http://www.wowinterface.com/downloads/author-230732.html

**Comment by jabernat** [comment]
Alright, I've made you the owner on CurseForge, and in WoWInterface the best I could do was add you as a team member. I'll make a post on their forum, to swap ownership and to bring it out of the "Discontinued and Outdated Mods" category.

Thanks for keeping this mod alive!

**Comment by spiralofhope** [comment]
@Ketho are you still maintaining that project?

**Comment by Ketho** [comment]
I wasn't but now I will

**Pull request merged**
